### ISSUE TITLE
[BUG] PACIFIC-1 client metadata for denom usei: key not found"

### ISSUE THREAD

**Issue by felipepimsil** [sei-protocol/sei-chain#1026]
**Seid version**
3.0.8

**Chain ID**
pacific-1

**Describe the bug**
Can't fetch DenomMetadata for `usei`. I could fetch for some tokens from factory.
When I fetch AllBalances from some account, it returns the denom "usei", so I don't know why the DenomMetadata endpoint returns `denom usei: key not found`

Tried with public rpcs (polkachu, brocha, rhino, etc) and with my own sei node.

**To Reproduce**
I'm using `cosmrs` to query `/cosmos.bank.v1beta1.Query/DenomMetadata`.
It is working in atlantic-2. But in pacific-1 I'm getting `AbciQuery { code: Err(22), log: "rpc error: code = NotFound desc = client metadata for denom usei: key not found", info: "", index: 0, key: [], value: [], proof: None, height: block::Height(18600300), codespace: "sdk" }`

code:
```
       let query = QueryDenomMetadataRequest {
            denom: denom.to_string(),
        };

        let request = self
            .rpc
            .abci_query(
                Some("/cosmos.bank.v1beta1.Query/DenomMetadata".to_string()),
                query.encode_to_vec(),
                None,
                false,
            )
            .await?;

        println!("{:?}", request);
```

**Expected behavior**
`usei` metadata is expected.

**Screenshots**

**Additional context**

EDIT:

Called `/cosmos.bank.v1beta1.Query/DenomsMetadata` to get all Denoms from `pacific-1` and noticed that `usei` isn't included, even it being returned in `AllBalances` queries. `DenomsMetadata` returned some tokens like BTC, USDT, ETH, etc. Maybe somehow `usei` isn't included in assetslist and is breaking some applications that make this request 😢

**Comment by yzang2019** [comment]
@felipepimsil Thanks for reporting this. This is expected because we haven't register usei denom metadata on pacific-1, it's not automatically, and right now it's available on testnet only. We will do that sometime in the future, but since environment is different, we can't assume everything works on testnet will also be the same on pacific-1. For now, you might wanna avoid query the denom metadata for usei

**Comment by philipsu522** [comment]
We will be adding usei to oracle price feeds which will set denom metadata. @felipepimsil we will circle back here when it's done.

**Comment by philipsu522** [comment]
this is now fixed:
```
 seid q bank denom-metadata --denom usei --node https://rpc.sei-apis.com                                   1 err | 10:48:50 AM
metadata:
  base: usei
  denom_units:
  - aliases:
    - microsei
    denom: usei
    exponent: 0
  - aliases:
    - millisei
    denom: msei
    exponent: 3
  - aliases: []
    denom: sei
    exponent: 6
  description: sei
  display: sei
  name: SEI
  symbol: SEI
```
